Fourth homework
Wojard/BI_2019_Python pull request #4
Opened 2019-10-23 04:46 UTC by Wojard

2019-10-27 15:46 UTC, AleksandrSl approved these changes
Хорошие решения!

2019-10-27 15:46 UTC, AleksandrSl commented on common_words.py
> +    second_list = list(second.split(','))
`split()`  и так возвращает `list`, не стоит делать лишних конвертаций

2019-10-27 15:46 UTC, AleksandrSl commented on create_Intervals.py
> +    data_list = sorted(list(data))
`sorted` прекрасно работает на `iterable` не надо конвертировать множество в список

2019-10-27 15:46 UTC, AleksandrSl commented on create_Intervals.py
> +    if len(data_list) == 0:
В таких случаях можно и просто `if data_list:`

2019-10-27 15:46 UTC, AleksandrSl commented on create_Intervals.py
> +    for i in range(len(data_list)):
Чтобы не писать `if i < len(data_list) - 1` достаточно в range сделать 
`for i in range(len(data_list) - 1)`

2019-10-27 15:46 UTC, AleksandrSl commented on create_Intervals.py
> +    start, end = min(data), min(data)
Можно и один раз посчитать
```
start = min(data)
end = start
```

2019-10-27 15:46 UTC, AleksandrSl commented on create_Intervals.py
> +    while end <= max(data):
Можно было и for использовать, чтобы руками не делать `end += 1`

2019-10-27 15:46 UTC, AleksandrSl commented on group_equal_consecutive.py
> +            current_list.append(els[i])
```
if i == 0 or els[i] != els[i - 1]:
    current_list = []    
current_list.append(els[i])
```

2019-10-27 15:47 UTC, AleksandrSl requested changes
Но некоторые замечания пожалуй можно поправить)

2019-10-29 17:51 UTC, Wojard commented
> ./create_Intervals.py:14:1: E305 expected 2 blank lines after class or function definition, found 1
Но их там две, почему так? :/

2019-11-02 13:59 UTC, merged